# -*- coding: cp1252 -*-
# ------------------------------------------------------------------------------------------
# CreateTiles_SMOD.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Creates tiles for SMOD and POP. Renames tiles
# ------------------------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

from datetime import datetime
starttime=datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
GHS_SMOD = "F:\\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0_mod20.tif"
GHS_POP = "F:\\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0.tif"
SMODTilesDir ="F:\\JRC-FAO\\Data\\1_Input\\GHSL\\SMODTiles"
POPTilesDir = "F:\\JRC-FAO\\Data\\1_Input\\GHSL\\POPTiles"

#SMOD Tiles names for renaming
SMOtile00 = SMODTilesDir + "\\GHS_SMOD_0.TIF"
SMOtile01 = SMODTilesDir + "\\GHS_SMOD_1.TIF"
SMOtile02 = SMODTilesDir + "\\GHS_SMOD_2.TIF"
SMOtile03 = SMODTilesDir + "\\GHS_SMOD_3.TIF"
SMOtile04 = SMODTilesDir + "\\GHS_SMOD_4.TIF"
SMOtile05 = SMODTilesDir + "\\GHS_SMOD_5.TIF"
SMOtile06 = SMODTilesDir + "\\GHS_SMOD_6.TIF"
SMOtile07 = SMODTilesDir + "\\GHS_SMOD_7.TIF"
SMOtile08 = SMODTilesDir + "\\GHS_SMOD_8.TIF"
SMOtile09 = SMODTilesDir + "\\GHS_SMOD_9.TIF"
NSMOtile00 = SMODTilesDir + "\\GHS_SMOD_00.TIF"
NSMOtile01 = SMODTilesDir + "\\GHS_SMOD_01.TIF"
NSMOtile02 = SMODTilesDir + "\\GHS_SMOD_02.TIF"
NSMOtile03 = SMODTilesDir + "\\GHS_SMOD_03.TIF"
NSMOtile04 = SMODTilesDir + "\\GHS_SMOD_04.TIF"
NSMOtile05 = SMODTilesDir + "\\GHS_SMOD_05.TIF"
NSMOtile06 = SMODTilesDir + "\\GHS_SMOD_06.TIF"
NSMOtile07 = SMODTilesDir + "\\GHS_SMOD_07.TIF"
NSMOtile08 = SMODTilesDir + "\\GHS_SMOD_08.TIF"
NSMOtile09 = SMODTilesDir + "\\GHS_SMOD_09.TIF"

#POP Tiles names for renaming
POPtile00 = POPTilesDir + "\\GHS_POP_0.TIF"
POPtile01 = POPTilesDir + "\\GHS_POP_1.TIF"
POPtile02 = POPTilesDir + "\\GHS_POP_2.TIF"
POPtile03 = POPTilesDir + "\\GHS_POP_3.TIF"
POPtile04 = POPTilesDir + "\\GHS_POP_4.TIF"
POPtile05 = POPTilesDir + "\\GHS_POP_5.TIF"
POPtile06 = POPTilesDir + "\\GHS_POP_6.TIF"
POPtile07 = POPTilesDir + "\\GHS_POP_7.TIF"
POPtile08 = POPTilesDir + "\\GHS_POP_8.TIF"
POPtile09 = POPTilesDir + "\\GHS_POP_9.TIF"
NPOPtile00 = POPTilesDir + "\\GHS_POP_00.TIF"
NPOPtile01 = POPTilesDir + "\\GHS_POP_01.TIF"
NPOPtile02 = POPTilesDir + "\\GHS_POP_02.TIF"
NPOPtile03 = POPTilesDir + "\\GHS_POP_03.TIF"
NPOPtile04 = POPTilesDir + "\\GHS_POP_04.TIF"
NPOPtile05 = POPTilesDir + "\\GHS_POP_05.TIF"
NPOPtile06 = POPTilesDir + "\\GHS_POP_06.TIF"
NPOPtile07 = POPTilesDir + "\\GHS_POP_07.TIF"
NPOPtile08 = POPTilesDir + "\\GHS_POP_08.TIF"
NPOPtile09 = POPTilesDir + "\\GHS_POP_09.TIF"

# Create Tiles for SMOD and POP
print 'Tiling SMOD and POP...'
arcpy.SplitRaster_management(GHS_SMOD,SMODTilesDir, "GHS_SMOD_","SIZE_OF_TILE","TIFF","NEAREST","11 4","3227 3809","0","PIXELS","#","#")
arcpy.Rename_management(SMOtile00, NSMOtile00)
arcpy.Rename_management(SMOtile01, NSMOtile01)
arcpy.Rename_management(SMOtile02, NSMOtile02)
arcpy.Rename_management(SMOtile03, NSMOtile03)
arcpy.Rename_management(SMOtile04, NSMOtile04)
arcpy.Rename_management(SMOtile05, NSMOtile05)
arcpy.Rename_management(SMOtile06, NSMOtile06)
arcpy.Rename_management(SMOtile07, NSMOtile07)
arcpy.Rename_management(SMOtile08, NSMOtile08)
arcpy.Rename_management(SMOtile09, NSMOtile09)
print 'SMOD tiled  - ', datetime.now().strftime('%Y-%m-%d %H:%M:%S')

arcpy.SplitRaster_management(GHS_POP,POPTilesDir, "GHS_POP_","SIZE_OF_TILE","TIFF","NEAREST","11 4","3227 3809","0","PIXELS","#","#")
arcpy.Rename_management(POPtile00, NPOPtile00)
arcpy.Rename_management(POPtile01, NPOPtile01)
arcpy.Rename_management(POPtile02, NPOPtile02)
arcpy.Rename_management(POPtile03, NPOPtile03)
arcpy.Rename_management(POPtile04, NPOPtile04)
arcpy.Rename_management(POPtile05, NPOPtile05)
arcpy.Rename_management(POPtile06, NPOPtile06)
arcpy.Rename_management(POPtile07, NPOPtile07)
arcpy.Rename_management(POPtile08, NPOPtile08)
arcpy.Rename_management(POPtile09, NPOPtile09)
print 'POP tiled  - ', datetime.now().strftime('%Y-%m-%d %H:%M:%S')

endtime=datetime.now()
totaltime= endtime-starttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '


