# ---------------------------------------------------------------------------
# Merge_RAC.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Select the most frequent RAC from three RAC layers.
# ---------------------------------------------------------------------------

import arcpy
from arcpy import env
import os
import os.path
import StringIO
from arcpy.sa import *

from datetime import datetime
firststarttime = datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
CCI_RAC_Mosaic = "F:\\JRC-FAO\\Data\\1_Input\\LC\\CCI\\CCI_RAC_Mosaic.gdb\\CCI_RAC_1km"
GL30_RAC_Mosaic = "F:\\JRC-FAO\\Data\\1_Input\\LC\\GlobeLand30\\GL30_RAC_Mosaic.gdb\\GL30_RAC_1km"
GLC_RAC_Tiles = "F:\\JRC-FAO\\Data\\1_Input\\LC\\GLCShare\\GLC_RAC_Tiles\\"
outdir = "F:\\JRC-FAO\\Data\\2_Outputs\Best_RAC\\"

# intermediate layers
GLC_RAC_TilesBEST_RAC_step1 = "BEST_RAC_step1"
BEST_RAC_step2 = "BEST_RAC_step2"
mask1 = "mask1"
posras = "posras"
pick = "pick"
pick2 = "pick2"
resamp = "resamp"
fill = "fill"
racfill = "racfill"
racrecl1 = "racrecl1"
racrecl2 = "racrecl2"
whereClause = "VALUE = 0"
BEST_RAC = "BEST_RAC_"

for root, dirs, files in os.walk(GLC_RAC_Tiles):
   for name in files:       
       fullfilename = os.path.join(root, name)
       filename = os.path.join(name)
       rootname = os.path.splitext(filename)[0]
       tilenumber= filename[8:10]
       extension = os.path.splitext(filename)[1]
       if extension == ".tif":
           starttime = datetime.now()
           outstep1 = outdir + BEST_RAC_step1 + tilenumber + ".tif"
           outstep2 = outdir + BEST_RAC_step2 + tilenumber + ".tif"
           outstep3 = outdir + mask1 + tilenumber + ".tif"
           outstep4 = outdir + posras + tilenumber + ".tif"
           outstep5 = outdir + pick + tilenumber + ".tif"
           outstep6 = outdir + resamp + tilenumber + ".tif"
           outstep7 = outdir + pick2 + tilenumber + ".tif"
           outstepf = outdir + racfill + tilenumber + ".tif"
           glcfill = outdir + fill + tilenumber + ".tif"
           bestrcl1 = outdir + racrecl1 + tilenumber + ".tif"
           bestrcl2 = outdir + racrecl2 + tilenumber + ".tif"
           final = outdir + BEST_RAC + tilenumber + ".tif"
           bound=arcpy.Describe(fullfilename)
           XMOLLmin=bound.extent.Xmin
           YMOLLmin=bound.extent.Ymin
           XMOLLmax=bound.extent.Xmax
           YMOLLmax=bound.extent.Ymax - 1000
           coordMOLL = str(XMOLLmin) + " " + str(YMOLLmin) + " " + str(XMOLLmax) + " " + str(YMOLLmax)
           if arcpy.Exists(final):
              print filename, ' already processed'
           else:
              # determines most frequent RAC class
              celsta1 = CellStatistics([fullfilename, CCI_RAC_Mosaic, GL30_RAC_Mosaic],"MAJORITY","DATA")
              celsta1.save(outstep1)
              # determines the class with minimum RAC value             
              celsta2 = CellStatistics([fullfilename, CCI_RAC_Mosaic, GL30_RAC_Mosaic],"MINIMUM","DATA")
              celsta2.save(outstep2)
              # selects pixels with 'NO DATA' value and replace them with the minimum value
              recla3 = Reclassify(outstep1,"Value","1 NODATA;2 NODATA;3 NODATA;4 NODATA;5 NODATA; NODATA 1","NODATA")
              recla3.save(outstep3)
              recla4 = Reclassify(outstep1,"Value","1 1;2 1;3 1;4 1;5 1;NODATA 2","NODATA")
              recla4.save(outstep4)
              racholes = Raster(outstep2) * Raster(outstep3)
              outpick = Pick(outstep4, [outstep1, racholes])
              outpick.save(outstep5)
              # Replaces values 0 (NoData in GLC_RAC and no majority) with the most frequent value in the surroundings
              focstat = FocalStatistics(fullfilename, NbrRectangle(5, 5, "CELL"),"MAJORITY", "NODATA")
              focstat.save(glcfill)
              recla5 = Reclassify(outstep5,"Value","0 1; 1 NODATA;2 NODATA;3 NODATA;4 NODATA;5 NODATA","NODATA")
              recla5.save(bestrcl1)
              recla6 = Reclassify(outstep5,"Value","0 2; 1 1;2 1;3 1;4 1;5 1","NODATA")
              recla6.save(bestrcl2)
              racholes2 = Raster(glcfill) * Raster(bestrcl1)
              outpick2 = Pick(bestrcl2, [outstep5, racholes2])
              outpick2.save(outstep7)
              zeronul = SetNull(outstep7, outstep7, whereClause)
              zeronul.save(outstepf)
              #Resamples output to 1000m (solves bug in management of mosaic resolution)
              arcpy.env.snapRaster = fullfilename
              arcpy.Resample_management(outstepf,outstep6,"1000","NEAREST")
              arcpy.Clip_management(outstep6, coordMOLL, final, fullfilename,"#","NONE")
              arcpy.BuildPyramids_management(final)
              arcpy.ClearEnvironment("snapRaster")
              #Deletes intermediate files
              arcpy.Delete_management(outstep1)
              arcpy.Delete_management(outstep2)
              arcpy.Delete_management(outstep3)
              arcpy.Delete_management(outstep4)
              arcpy.Delete_management(outstep5)
              arcpy.Delete_management(outstep6)
              arcpy.Delete_management(outstep7)
              arcpy.Delete_management(glcfill)
              arcpy.Delete_management(outstepf)
              arcpy.Delete_management(bestrcl1)
              arcpy.Delete_management(bestrcl2)
              arcpy.Delete_management(racholes)
              arcpy.Delete_management(racholes2)              
              endtime = datetime.now()
              totaltime = endtime - starttime   
              print 'Tile n. ', tilenumber, 'processed in ', totaltime

print ' '
lasttime = datetime.now()
lasttotaltime = lasttime - firststarttime
print 'END OF PROCEDURE - total elapsed time: ', lasttotaltime

           
