# -*- coding: cp1252 -*-
# ---------------------------------------------------------------------------
# Process_SMOD.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Modify SMOD classes using POP (threshold for POP <= 20 p/km2)
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

from datetime import datetime
starttime=datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
GHS_SMOD = "F:\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0.tif"
GHS_POP = "F:\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0.tif"
GHS_POP_rcl = "F:\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0\\GHS_POP_rcl.tif"
GHS_POP_pos = "F:\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0\\GHS_POP_pos.tif"
GHS_SMOD_tmp = "F:\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0_tmp.tif"
GHS_SMOD_mod = "F:\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0_mod20.tif"

#Process: Modify SMOD classes using POP (threshold for POP <= 20 p/km2)
rast = arcpy.Raster(GHS_POP)
newclasses = RemapRange([[0, 20, 0],[20.0000001, rast.maximum, "NODATA"]])
outreclass1= arcpy.sa.Reclassify(GHS_POP,"VALUE",newclasses,"NODATA")
outreclass1.save(GHS_POP_rcl)
posrast = RemapRange([[0, 1],["NODATA", 2]])
outreclass2= arcpy.sa.Reclassify(GHS_POP_rcl,"VALUE",posrast,"NODATA")
outreclass2.save(GHS_POP_pos)
outPick = Pick(GHS_POP_pos, [GHS_POP_rcl, GHS_SMOD])
outPick.save(GHS_SMOD_tmp)
whereClause = "VALUE >= 2"
outCon = Con(GHS_SMOD, GHS_SMOD, GHS_SMOD_tmp, whereClause)
outCon.save(GHS_SMOD_mod)
arcpy.BuildPyramids_management(GHS_SMOD_mod)

arcpy.Delete_management(GHS_POP_rcl)
arcpy.Delete_management(GHS_POP_pos)
arcpy.Delete_management(GHS_SMOD_tmp)


endtime=datetime.now()
totaltime= endtime-starttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '



