# ---------------------------------------------------------------------------
# Project_GL30.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Reprojects GlobeLand 30 tiles in Mollweide.
# UTM Zones N01, N59, N60, S01 and S60 are reprojected in Mollweide Pacific (central Meridian: -180)
# ---------------------------------------------------------------------------

import arcpy
from arcpy import env
import os
import os.path
import StringIO

from datetime import datetime
starttime = datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
# MOLLpacific is a custom projection, equal to Mollweide (world) except for Central Meridian (-180 instead of 0)
outdir = "F:\\JRC-FAO\\Data\\1_Input\\LC\\GlobeLand30\TilesMOLL\\"
MOLLpacific = "C:\\Program Files (x86)\\ArcGIS\\Desktop10.0\\Coordinate Systems\\Projected Coordinate Systems\\World\\Mollweide (Pacific).prj"
MOLLworld = "C:\\Program Files (x86)\\ArcGIS\\Desktop10.0\\Coordinate Systems\\Projected Coordinate Systems\\World\\Mollweide (world).prj"
origtiles = "F:\\JRC-FAO\\Data\\1_Input\\LC\\GlobeLand30\OrigTiles"

# Process: project GL30 tiles in Mollweide (N.B.: very time consuming)
for root, dirs, files in os.walk(origtiles):
   for name in files:       
       fullfilename = os.path.join(root, name)
       filename = os.path.join(name)
       extension = os.path.splitext(filename)[1] 
       if extension == ".tif":
           starttime = datetime.now()
           outfile= outdir + filename
           desc = arcpy.Describe(fullfilename).spatialReference
           if arcpy.Exists(outfile):
              print filename, ' already processed'
           else:
              if (desc.name == 'WGS_84_UTM_zone_1N') or (desc.name == 'WGS_84_UTM_zone_59N') or (desc.name == 'WGS_84_UTM_zone_60N') or (desc.name == 'WGS_84_UTM_zone_1S') or (desc.name == 'WGS_84_UTM_zone_60S'):
                    outcoordsys = MOLLpacific
                    arcpy.ProjectRaster_management(fullfilename,outfile,outcoordsys,"NEAREST","30","#","#","")
                    label= outcoordsys[96:130]
                    endtime = datetime.now()
                    totaltime = endtime - starttime   
                    print filename, ' projected in ', label, ' in ', totaltime 
              else:
                    outcoordsys = MOLLworld
                    arcpy.ProjectRaster_management(fullfilename,outfile,outcoordsys,"NEAREST","30","#","#","")
                    label= outcoordsys[96:130]
                    endtime = datetime.now()
                    totaltime = endtime - starttime   
                    print filename, ' projected in ', label, ' in ', totaltime
print ' '
lasttime = datetime.now()
lasttotaltime = lasttime - starttime
print 'END OF PROCEDURE - total elapsed time: ', lasttotaltime

           
