# ---------------------------------------------------------------------------
# Combine_smod_rac_1country.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Reclasses GLC tiles into Rural Activity Classes, using a table stored in LandCover.gdb.
# ---------------------------------------------------------------------------

import arcpy
from arcpy import env
import os
import os.path
import StringIO
from arcpy.sa import *

from datetime import datetime
firststarttime = datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
outdir = "F:\\JRC-FAO\\Data\\1_Input\\LC\\GLCShare\\GLC_RAC_Tiles\\"
Reclass_GLC = "F:\\JRC-FAO\\Data\\1_Input\\LC\\LandCover.gdb\\Reclass_GLC"
GLCTiles = "F:\\JRC-FAO\\Data\\1_Input\\LC\\GLCShare\\GLCTiles\\"

# Process: reclass GLC tiles
for root, dirs, files in os.walk(GLCTiles):
   for name in files:
       fullfilename = os.path.join(root, name)
       filename = os.path.join(name)
       rootname = os.path.splitext(filename)[0]
       rootname2 = rootname[0:4]
       tilenum = rootname[4:6]
       extension = os.path.splitext(filename)[1] 
       if extension == ".TIF":
           starttime = datetime.now()
           outfile1= outdir + rootname2 + "tmp_" + tilenum + ".tif"
           outfile2= outdir + rootname2 + "RAC_" + tilenum + ".tif"
           if arcpy.Exists(outfile2):
              print filename, ' already processed'
           else:
              arcpy.gp.ReclassByTable_sa(fullfilename, Reclass_GLC, "FromValue", "ToValue", "NewValue", outfile1, "NODATA")
              arcpy.CopyRaster_management(outfile1,outfile2,"#","#","#","NONE","NONE","8_BIT_UNSIGNED")
              arcpy.Delete_management(outfile1)
              endtime = datetime.now()
              totaltime = endtime - starttime   
              print filename, ' reclassed in ', totaltime
print ' '
lasttime = datetime.now()
lasttotaltime = lasttime - firststarttime
print 'END OF PROCEDURE - total elapsed time: ', lasttotaltime
