# -*- coding: cp1252 -*-
# ---------------------------------------------------------------------------
# SummGAULAreas_World_level2.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Perform summary analisys for all countries at level 2
# ---------------------------------------------------------------------------


# Import arcpy module
import arcpy
from arcpy import env
import os
import os.path
import StringIO

from datetime import datetime
firststarttime=datetime.now()
print ' '
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True
arcpy.env.qualifiedFieldNames = False
arcpy.env.workspace = "F:\\JRC-FAO\\Data\\2_Outputs\\CountryStats\\StatsGAUL_Level2.gdb"

# Local Variables (TO BE EDITED BY THE USER)
gaul_pol = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\g2015_2014_2_54009"
countrylist = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\GAUL_CountryList"

# Local Variables (NO EDIT)
STATStable = "TabAreas_SMOD_RAC_world"
COUNTRYtable = "SUM_L2_World"

# Join the table with tabulated areas
arcpy.env.qualifiedFieldNames = False
arcpy.MakeFeatureLayer_management(gaul_pol, "gaul_lyr")
fc = "gaul_lyr"
arcpy.AddJoin_management(fc, "OBJECTID", STATStable, "VALUE", "KEEP_ALL")
print 'Tables joined'

# Iterate statistics for each country
casefield = "g2015_2014_2_54009.UniqueID"
stats = [["g2015_2014_2_54009.ISO3", "FIRST"], ["g2015_2014_2_54009.ADM0_NAME", "FIRST"], ["g2015_2014_2_54009.ADM1_NAME", "FIRST"],  ["g2015_2014_2_54009.ADM2_NAME", "FIRST"]]
for field in arcpy.ListFields(fc, "*VALUE_*"):                     
    stats.append([field.name, "SUM"])
arcpy.Statistics_analysis(fc, COUNTRYtable, stats, casefield)
endtime=datetime.now()
totaltime= endtime-firststarttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '

