# -*- coding: cp1252 -*-
# ------------------------------------------------------------------------------------------
# Combine_smod_rac.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Combine SMOD and RAC, aggregate classes and makes mosaic layer
# ------------------------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
import os
import os.path
import StringIO
from arcpy.sa import *

from datetime import datetime
firststarttime=datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
SMOD_TilesDir ="F:\\JRC-FAO\\Data\\1_Input\\GHSL\\SMODTiles\\"
POP_TilesDir = "F:\\JRC-FAO\\Data\\1_Input\\GHSL\\POPTiles\\"
BESTRAC_TilesDir ="F:\\JRC-FAO\\Data\\2_Outputs\\Best_RAC\\"
outdir = "F:\\JRC-FAO\\Data\\2_Outputs\\SMOD_RAC\\"

# Local Variables (NO EDIT)
BEST_RAC = "BEST_RAC_"
Cmb_SMOD_RACtmp = "Cmb_SMOD_RACtmp_"
Cmb_SMOD_RAC = "Cmb_SMOD_RAC_"
SMOD_RAC = "SMOD_RAC_"
SMOD_RAC_mos = "SMOD_RAC_mos.tif"
fullmosname = outdir + SMOD_RAC_mos

#Step 1 : Combine SMOD and BEST_RAC
print 'Step 1: combining SMOD and BEST_RAC'
remap = RemapValue([[4, 40],[14, 40],[24, 40],[32, 31], [33, 31], [34, 31],[15, 5], [25, 5], [35, 5]])
for root, dirs, files in os.walk(SMOD_TilesDir):
   for name in files:       
       fullfilename = os.path.join(root, name)
       filename = os.path.join(name)
       rootname = os.path.splitext(filename)[0]
       tilenumber= filename[9:11]
       extension = os.path.splitext(filename)[1]
       if extension == ".TIF":
           starttime = datetime.now()
           RACtile = BESTRAC_TilesDir + BEST_RAC + tilenumber + ".tif"
           final1 = outdir + Cmb_SMOD_RACtmp + tilenumber + ".tif"
           final2 = outdir + Cmb_SMOD_RAC + tilenumber + ".tif"
           if arcpy.Exists(final2):
               print 'Tile n.', tilenumber, ' already processed'
           else:
               # Process: Combine SMOD and RAC
               Cmb_smod_RAC = Combine([fullfilename,RACtile])
               Cmb_smod_RAC.save(final1)
               arcpy.AddField_management(final1, "CombCODE", "SHORT", "", "", "", "CombCode", "NULLABLE", "NON_REQUIRED", "")
               def getFieldNames(tif):
                   fieldnames = [f.name for f in arcpy.ListFields(tif)]
                   return fieldnames
               fieldnames = getFieldNames(final1)
               SMODfield = fieldnames[3]
               RACfield = fieldnames[4]
               expression = "[" + SMODfield + "]" + "*10" + " + [" + RACfield + "]"
               arcpy.CalculateField_management(final1,"CombCode",expression,"VB","#")
               # Process: Aggregates water bodies classes, Urban classes, Unproductive classes and and reclass
               outReclassify = Reclassify(final1, "CombCode", remap, "DATA")
               outReclassify.save(final2)
               arcpy.Delete_management(final1)
               endtime = datetime.now()
               totaltime = endtime - starttime   
               print 'Tile n.', tilenumber, 'processed in ', totaltime
print 'Step 1 completed '


#Step 2 : Making SMOD_RAC mosaic
print 'Step 2: Making SMOD_RAC mosaic'
arcpy.CreateRasterDataset_management(outdir,SMOD_RAC_mos,"1000","8_BIT_UNSIGNED","PROJCS['World_Mollweide',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mollweide'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]]","1","#","PYRAMIDS -1 NEAREST DEFAULT 75","128 128","LZ77","-18040095.1961317 9020047.34806998")
arcpy.WorkspaceToRasterDataset_management(outdir,fullmosname,"NONE","LAST","FIRST","#","#","NONE","0","NONE","NONE")
print 'Mosaic created. Building pyramids and attribute table...'
arcpy.BuildRasterAttributeTable_management(fullmosname,"Overwrite")
arcpy.BuildPyramids_management(fullmosname)
arcpy.AddField_management(fullmosname, "Label", "TEXT", "", "", "256", "ClassLabel", "NULLABLE", "NON_REQUIRED", "")
print 'Step 2 completed'
print ' '

endtime=datetime.now()
totaltime= endtime-firststarttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '


