# -*- coding: cp1252 -*-
# ------------------------------------------------------------------------------------------
# CreateTilse_GLC_CCIy.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Creates tiles for GLC and CCI. Renames tiles for GLC
# ------------------------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

from datetime import datetime
starttime=datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
GHS_SMOD = "F:\\JRC-FAO\\Data\\2_Input\\GHSL\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0.tif"
ESACCI_LC = "F:\\JRC-FAO\\Data\\2_Input\\LC\\CCI\\ESACCI-LC-L4-LCCS-Map-300m-P1Y-2015-v2.0.7.tif"
GLCSHARE = "F:\\JRC-FAO\\Data\\2_Input\\LC\\GLCShare\\glc_shv10_DOM.Tif"
GLCSHAREMOLL = "F:\\JRC-FAO\\Data\\2_Input\\LC\\GLCShare\\GLC_MOLL_tmp.Tif"
GLCSHAREMOLL_Clip = "F:\\JRC-FAO\\Data\\2_Input\\LC\\GLCShare\\GLC_MOLL.Tif"
ESACCI_LCMOLL ="F:\\JRC-FAO\\Data\\2_Input\\LC\\CCI\\ESACCI_LC_MOLL.tif"
ESACCI_LCMOLL_Clip ="F:\\JRC-FAO\\Data\\2_Input\\LC\\CCI\\ESACCI_LC_MOLL_Clip.tif"
GLCTilesDir ="F:\\JRC-FAO\\Data\\2_Input\\LC\\GLCShare\\GLCTiles"
CCITilesDir = "F:\\JRC-FAO\\Data\\2_Input\\LC\\CCI\\CCITiles"

#GLC Tiles names for renaming
GLCtile00 = GLCTilesDir + "\\GLC_0.TIF"
GLCtile01 = GLCTilesDir + "\\GLC_1.TIF"
GLCtile02 = GLCTilesDir + "\\GLC_2.TIF"
GLCtile03 = GLCTilesDir + "\\GLC_3.TIF"
GLCtile04 = GLCTilesDir + "\\GLC_4.TIF"
GLCtile05 = GLCTilesDir + "\\GLC_5.TIF"
GLCtile06 = GLCTilesDir + "\\GLC_6.TIF"
GLCtile07 = GLCTilesDir + "\\GLC_7.TIF"
GLCtile08 = GLCTilesDir + "\\GLC_8.TIF"
GLCtile09 = GLCTilesDir + "\\GLC_9.TIF"
NGLCtile00 = GLCTilesDir + "\\GLC_00.TIF"
NGLCtile01 = GLCTilesDir + "\\GLC_01.TIF"
NGLCtile02 = GLCTilesDir + "\\GLC_02.TIF"
NGLCtile03 = GLCTilesDir + "\\GLC_03.TIF"
NGLCtile04 = GLCTilesDir + "\\GLC_04.TIF"
NGLCtile05 = GLCTilesDir + "\\GLC_05.TIF"
NGLCtile06 = GLCTilesDir + "\\GLC_06.TIF"
NGLCtile07 = GLCTilesDir + "\\GLC_07.TIF"
NGLCtile08 = GLCTilesDir + "\\GLC_08.TIF"
NGLCtile09 = GLCTilesDir + "\\GLC_09.TIF"

# Create Tiles for GLC Share
# Process: Project GLC in MOLLWEIDE and Clip it on SMOD with snapping
print 'Projecting and clipping GLC...'
arcpy.env.snapRaster = GHS_SMOD
arcpy.ProjectRaster_management(GLCSHARE, GLCSHAREMOLL, "PROJCS['World_Mollweide',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mollweide'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]]", "NEAREST", "1000", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
arcpy.Clip_management(GLCSHAREMOLL,"-17619594.5474435 -6484970.53813151 17876405.4525565 8751029.46186849",GLCSHAREMOLL_Clip,GHS_SMOD,"#","NONE")
print 'GLC projected and clipped - ', datetime.now().strftime('%Y-%m-%d %H:%M:%S')
arcpy.SplitRaster_management(GLCSHAREMOLL_Clip,GLCTilesDir, "GLC_","SIZE_OF_TILE","TIFF","NEAREST","#","3227 3809","0","PIXELS","#","#")
arcpy.ClearEnvironment("snapRaster")
arcpy.Rename_management(GLCtile00, NGLCtile00)
arcpy.Rename_management(GLCtile01, NGLCtile01)
arcpy.Rename_management(GLCtile02, NGLCtile02)
arcpy.Rename_management(GLCtile03, NGLCtile03)
arcpy.Rename_management(GLCtile04, NGLCtile04)
arcpy.Rename_management(GLCtile05, NGLCtile05)
arcpy.Rename_management(GLCtile06, NGLCtile06)
arcpy.Rename_management(GLCtile07, NGLCtile07)
arcpy.Rename_management(GLCtile08, NGLCtile08)
arcpy.Rename_management(GLCtile09, NGLCtile09)
print 'GLC tiled - ', datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Create Tiles for ESA CCI
# Process: Project CCI in MOLLWEIDE and Clip it on SMOD with snapping
print 'Projecting and clipping CCI...'
arcpy.env.snapRaster = GHS_SMOD
arcpy.ProjectRaster_management(ESACCI_LC, ESACCI_LCMOLL, "PROJCS['World_Mollweide',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],                               PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mollweide'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]]", "NEAREST", "", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
print 'CCI projected - ', datetime.now().strftime('%Y-%m-%d %H:%M:%S')
arcpy.Clip_management(ESACCI_LCMOLL,"-17619594.5474435 -6484970.53813151 17877405.4525565 8751029.46186849",ESACCI_LCMOLL_Clip,GHS_SMOD,"#","NONE")
print 'CCI clipped - ', datetime.now().strftime('%Y-%m-%d %H:%M:%S')
arcpy.SplitRaster_management(ESACCI_LCMOLL_Clip,CCITilesDir, "CCI_","NUMBER_OF_TILES","TIFF","NEAREST","10 6","#","0","PIXELS","#","#")
arcpy.ClearEnvironment("snapRaster")
print 'CCI tiled - ', datetime.now().strftime('%Y-%m-%d %H:%M:%S')
   
# Delete intermediate files
arcpy.Delete_management(GLCSHAREMOLL)
arcpy.Delete_management(ESACCI_LCMOLL)
arcpy.Delete_management(ESACCI_LCMOLL_Clip)

endtime=datetime.now()
totaltime= endtime-starttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '


