# -*- coding: cp1252 -*-
# ------------------------------------------------------------------------------------------
# Combine_smod_rac_1country.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Creates population statistics by SMOD_RAC class
# ------------------------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

from datetime import datetime
starttime=datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Define workspace
arcpy.env.workspace = "F:/JRC-FAO/Data/2_Outputs/CountryStats/StatsGAUL_Level2.gdb/"

# Local Variables (TO BE EDITED BY THE USER)
GHS_POP = "F:\\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0\\GHS_POP_GPW42015_GLOBE_R2015A_54009_1k_v1_0.tif"
SMOD_RAC_mos = "F:\\JRC-FAO\\Data\\2_Outputs\\SMOD_RAC\\SMOD_RAC_mos_aggregated.tif"
admraster = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\GAUL2015.gdb\\gaul_54009_500"

# Local Variables (NO EDIT)
CL01 = "Pop_CL01"
CL02 = "Pop_CL02"
CL03 = "Pop_CL03"
CL40 = "Pop_CL40"
CL05 = "Pop_CL05"
CL11 = "Pop_CL11"
CL12 = "Pop_CL12"
CL13 = "Pop_CL13"
CL21 = "Pop_CL21"
CL22 = "Pop_CL22"
CL23 = "Pop_CL23"
CL31 = "Pop_CL31"

#Creates POP layers for each SMOD-RAC class
whereclause = "VALUE = 1"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL01)
print outcon, 'exported'

whereclause = "VALUE = 2"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL02)
print outcon, 'exported'

whereclause = "VALUE = 3"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL03)
print outcon, 'exported'

whereclause = "VALUE = 40"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL40)
print outcon, 'exported'

whereclause = "VALUE = 5"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL05)
print outcon, 'exported'

whereclause = "VALUE = 11"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL11)
print outcon, 'exported'

whereclause = "VALUE = 12"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL12)
print outcon, 'exported'

whereclause = "VALUE = 13"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL13)
print outcon, 'exported'

whereclause = "VALUE = 21"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL21)
print outcon, 'exported'

whereclause = "VALUE = 22"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL22)
print outcon, 'exported'

whereclause = "VALUE = 23"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL23)
print outcon, 'exported'

whereclause = "VALUE = 31"
outcon = Con(SMOD_RAC_mos,GHS_POP,"0",whereclause)
outcon.save(CL31)
print outcon, 'exported'

#Creates Zonal statistics tables of population for each SMOR-RAC class

outstats = ZonalStatisticsAsTable(admraster,"Value",CL01,"ZonalSt_POP_CL01","DATA","SUM")
print CL01, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL02,"ZonalSt_POP_CL02","DATA","SUM")
print CL02, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL03,"ZonalSt_POP_CL03","DATA","SUM")
print CL03, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL40,"ZonalSt_POP_CL40","DATA","SUM")
print CL40, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL05,"ZonalSt_POP_CL05","DATA","SUM")
print CL05, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL11,"ZonalSt_POP_CL11","DATA","SUM")
print CL11, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL12,"ZonalSt_POP_CL12","DATA","SUM")
print CL12, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL13,"ZonalSt_POP_CL13","DATA","SUM")
print CL13, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL21,"ZonalSt_POP_CL21","DATA","SUM")
print CL21, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL22,"ZonalSt_POP_CL22","DATA","SUM")
print CL22, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL23,"ZonalSt_POP_CL23","DATA","SUM")
print CL23, 'done'
outstats = ZonalStatisticsAsTable(admraster,"Value",CL31,"ZonalSt_POP_CL31","DATA","SUM")
print CL31, 'done'

# Deletes Pop layers
arcpy.Delete_management(CL01)
arcpy.Delete_management(CL02)
arcpy.Delete_management(CL03)
arcpy.Delete_management(CL40)
arcpy.Delete_management(CL05)
arcpy.Delete_management(CL11)
arcpy.Delete_management(CL12)
arcpy.Delete_management(CL13)
arcpy.Delete_management(CL21)
arcpy.Delete_management(CL22)
arcpy.Delete_management(CL23)
arcpy.Delete_management(CL31)

endtime=datetime.now()
totaltime= endtime-starttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '
