# -*- coding: cp1252 -*-
# ---------------------------------------------------------------------------
# Process_Gaul.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Creates Country List, Projects Gaul in Mollweide and rasterize # it to 500 m
# ---------------------------------------------------------------------------

import arcpy
from arcpy import env
import os
import os.path
import StringIO

from datetime import datetime
firststarttime = datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True
env.workspace = "F:\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb"

# Local Variables (TO BE EDITED BY THE USER)
gaul_shp = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\g2015_2014_2.shp"
gaul_gdb = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb"
gaulMOLL  = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\g2015_2014_2_54009"
gaulcountrylist = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\GAUL_CountryList"
gaul500temp ="F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\gaul_54009_500tenp"
gaulMOLLras500 = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\gaul_54009_500"
GHS_SMOD = "F:\\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0.tif"

# Process: define GHS_SMOD boundaries
bound=arcpy.Describe(GHS_SMOD)
XMOLLmin=bound.extent.Xmin
YMOLLmin=bound.extent.Ymin
XMOLLmax=bound.extent.Xmax
YMOLLmax=bound.extent.Ymax
coordMOLL = str(XMOLLmin) + " " + str(YMOLLmin) + " " + str(XMOLLmax) + " " + str(YMOLLmax)

# Process: Project GAUL in Mollweide (54009)
from datetime import datetime
starttime = datetime.now()
arcpy.Project_management(gaul_shp, gaulMOLL,"PROJCS['World_Mollweide',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mollweide'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]]","#","GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
endtime=datetime.now()
totaltime = endtime - starttime   
print 'gaul reprojected in ', totaltime

# Process: Generate country list based on ISO3 code
statsFields = [["ADM0_CODE", "MIN"], ["ADM0_CODE", "MAX"], ["ADM0_NAME", "FIRST"], ["ADM0_NAME", "LAST"], ["STATUS", "FIRST"], ["STATUS", "LAST"]]
arcpy.Statistics_analysis(gaulMOLL,gaulcountrylist,statsFields,"ISO3")
print 'GAUL country list generated'

# Process: convert GAUL into raster (500m)
starttime=datetime.now()
arcpy.env.snapRaster = GHS_SMOD
arcpy.PolygonToRaster_conversion(gaulMOLL,"OBJECTID",gaul500temp,"CELL_CENTER","NONE","500")
arcpy.Clip_management(gaul500temp, coordMOLL, gaulMOLLras500, GHS_SMOD,"#","NONE")
arcpy.BuildPyramids_management(gaulMOLLras500)
arcpy.BuildRasterAttributeTable_management(gaulMOLLras500, "Overwrite")
arcpy.ClearEnvironment("snapRaster")
arcpy.Delete_management(gaul500temp)
endtime=datetime.now()
totaltime = endtime - starttime   
print 'gaul converted in raster 500m in ', totaltime

print ' '
lasttime = datetime.now()
lasttotaltime = lasttime - firststarttime
print 'END OF PROCEDURE - total elapsed time: ', lasttotaltime
