# ---------------------------------------------------------------------------
# Combine_smod_rac_1country.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Reclasses CCI tiles into Rural Activity Classes, using a table stored in LandCover.gdb.
# ---------------------------------------------------------------------------

import arcpy
from arcpy import env
import os
import os.path
import StringIO
from arcpy.sa import *

from datetime import datetime
firststarttime = datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
outdir = "F:\\JRC-FAO\\Data\\1_Input\\LC\\CCI\\CCI_RAC_Tiles\\"
Reclass_CCI = "F:\\JRC-FAO\\Data\\1_Input\\LC\\LandCover.gdb\\Reclass_CCI"
CCI_Tiles = "F:\\JRC-FAO\\Data\\1_Input\\LC\\CCI\\CCITiles\\"

# Process: reclass CCI tiles
n = 0

for root, dirs, files in os.walk(CCI_Tiles):
   for name in files:       
       fullfilename = os.path.join(root, name)
       filename = os.path.join(name)
       rootname = os.path.splitext(filename)[0] 
       rootname2 = rootname[0:4]
       extension = os.path.splitext(filename)[1] 
       if extension == ".TIF":
           n = n + 1
           starttime = datetime.now()
           if n < 10:
              serialnum = "0" + str(n)
           else:
              serialnum = str(n)
           outfile1= outdir + rootname2 + "tmp_" + serialnum + ".tif"
           outfile2= outdir + rootname2 + "RAC_" + serialnum + ".tif"
           if arcpy.Exists(outfile2):
              print filename, ' already processed'
           else:
              if filename == "CCI_50.TIF" or filename == "CCI_59.TIF":
                 print filename, " skipped"
              else:
                 arcpy.gp.ReclassByTable_sa(fullfilename, Reclass_CCI, "FromValue", "ToValue", "NewValue", outfile1, "NODATA")
                 arcpy.CopyRaster_management(outfile1,outfile2,"#","#","#","NONE","NONE","8_BIT_UNSIGNED")
                 arcpy.Delete_management(outfile1)
                 endtime = datetime.now()
                 totaltime = endtime - starttime   
                 print filename, ' reclassed in ', totaltime
print ' '
lasttime = datetime.now()
lasttotaltime = lasttime - firststarttime
print 'END OF PROCEDURE - total elapsed time: ', lasttotaltime

           
