# -*- coding: cp1252 -*-
# ---------------------------------------------------------------------------
# Resample_CCI_RAC.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Resamples CCI RAC tiles to 1km resolution, snap them to SMOD layer
# and creates the mosaic of resampled RAC tiles
# ---------------------------------------------------------------------------

import arcpy
from arcpy import env
import os
import os.path
import StringIO
from arcpy.sa import *

from datetime import datetime
firststarttime = datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
GHS_SMOD = "F:\\JRC-FAO\\Data\\1_Input\\GHSL\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0\\GHS_SMOD_POP2015_GLOBE_R2016A_54009_1k_v1_0.tif"
outdir = "F:\\JRC-FAO\\Data\\1_Input\\LC\\CCI\\CCI_RAC_Tiles_1km\\"
CCI_Mos_loc = "F:\\JRC-FAO\\Data\\1_Input\\LC\\CCI\\"
CCI_RAC_Tiles= "F:\\JRC-FAO\\Data\\1_Input\\LC\\CCI\\CCI_RAC_Tiles\\"

# Local Variables (NO EDIT)
CCI_Mos_gdb = "CCI_RAC_Mosaic.gdb"
CCI_Mos_fname = CCI_Mos_loc + CCI_Mos_gdb
RAC_Mos = "CCI_RAC_1km"

# Process: resample to 1 km
arcpy.env.snapRaster = GHS_SMOD

for root, dirs, files in os.walk(CCI_RAC_Tiles):
   for name in files:       
       fullfilename = os.path.join(root, name)
       filename = os.path.join(name)
       rootname = os.path.splitext(filename)[0] 
       extension = os.path.splitext(filename)[1] 
       if extension == ".tif":
           starttime = datetime.now()
           outfile1 = outdir + rootname + "_1km.tif"
           if arcpy.Exists(outfile1):
              print filename, ' already processed'
           else:
              arcpy.Resample_management(fullfilename,outfile1,"1000","MAJORITY")
              endtime = datetime.now()
              totaltime = endtime - starttime   
              print filename, ' resampled in ', totaltime

arcpy.ClearEnvironment("snapRaster")

# Process: create mosaic and add rasters
if arcpy.Exists(CCI_Mos_fname):
   print 'Mosaic aleady existing: please update rasters manually'
else:
   arcpy.CreateFileGDB_management(CCI_Mos_loc,CCI_Mos_gdb,"CURRENT")
   arcpy.CreateMosaicDataset_management(CCI_Mos_fname, RAC_Mos,"PROJCS['World_Mollweide',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mollweide'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]];-18040200 -9020200 249642444.505632;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision","1","8_BIT_UNSIGNED")
   arcpy.AddRastersToMosaicDataset_management(CCI_Mos_fname + "\\" + RAC_Mos,"Raster Dataset",outdir,"UPDATE_CELL_SIZES","UPDATE_BOUNDARY","UPDATE_OVERVIEWS","#","0","1500","#","#","SUBFOLDERS","ALLOW_DUPLICATES","BUILD_PYRAMIDS","CALCULATE_STATISTICS","BUILD_THUMBNAILS","#")
   arcpy.DefineMosaicDatasetNoData_management(CCI_Mos_fname + "\\" + RAC_Mos,"1","BAND_1 0","#","#")

print ' '
lasttime = datetime.now()
lasttotaltime = lasttime - firststarttime
print 'END OF PROCEDURE - total elapsed time: ', lasttotaltime

           
