# -*- coding: cp1252 -*-
# ---------------------------------------------------------------------------
# Summarize_Areas_AllCountries.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Perform summary analisys for all country at level 2
# ---------------------------------------------------------------------------


# Import arcpy module
import arcpy
from arcpy import env
import os
import os.path
import StringIO

from datetime import datetime
firststarttime=datetime.now()
print ' '
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True
arcpy.env.qualifiedFieldNames = False
env.workspace = "F:\\JRC-FAO\\Data\\2_Outputs\\CountryStats\\StatsGAUL_Level2.gdb"

# Local Variables (TO BE EDITED BY THE USER)
gaul_pol = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\g2015_2014_2_54009"
countrylist = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\\GAUL2015.gdb\\GAUL_CountryList"
STATStable = "F:\\JRC-FAO\\Data\\2_Outputs\\CountryStats\\StatsGAUL_Level2.gdb\\TabAreas_SMOD_RAC_LVST_world"
ADMlevel = "2"

# Join the table with tabulated areas
arcpy.env.qualifiedFieldNames = False
arcpy.MakeFeatureLayer_management(gaul_pol, "gaul_lyr")
fc = "gaul_lyr"
arcpy.AddJoin_management(fc, "OBJECTID", STATStable, "VALUE", "KEEP_ALL")
print 'Tables joined'

# Iterate statistics for each country
iso3field = "ISO3"
cursor = arcpy.SearchCursor(countrylist)
def buildWhereClause(table, field, value):
# Add DBMS-specific field delimiters
    fieldDelimited = arcpy.AddFieldDelimiters(table, field)
    value = "'%s'" % value
    # Format WHERE clause
    whereClause = "%s = %s" % (fieldDelimited, value)
    return whereClause

for row in cursor:
    starttime=datetime.now()
    inputtable = countrylist
    fieldname = "ISO3"
    fieldvalue = (row.getValue(iso3field))
    whereclause = buildWhereClause(countrylist, fieldname, fieldvalue)
    COUNTRYtable = "SUM_L" + ADMlevel + "_" + (row.getValue(iso3field)) + "_LVST" 
    if arcpy.Exists(COUNTRYtable):
        print fieldvalue, ' already processed'
    else:
        arcpy.SelectLayerByAttribute_management (fc, "NEW_SELECTION", whereclause)
        print(row.getValue(iso3field)) + ' selected'
        # Summarize data
        casefield = "g2015_2014_2_54009.ADM" + ADMlevel + "_CODE"
        stats = [["g2015_2014_2_54009.ISO3", "FIRST"], ["g2015_2014_2_54009.ADM0_NAME", "FIRST"], ["g2015_2014_2_54009.ADM1_NAME", "FIRST"],  ["g2015_2014_2_54009.ADM2_NAME", "FIRST"]]
        for field in arcpy.ListFields(fc, "*VALUE_*"):                     
            stats.append([field.name, "SUM"])
        arcpy.Statistics_analysis(fc, COUNTRYtable, stats, casefield)
        endtime=datetime.now()
        totaltime= endtime-starttime
        print(row.getValue(iso3field)), ' processed in ', totaltime
endtime=datetime.now()
totaltime= endtime-firststarttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '



