# -*- coding: cp1252 -*-
# ---------------------------------------------------------------------------
# Combine_smod_rac_1country.py
# Created on: 2017-08-10 10:48:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Tabulate SMOD_RAC areas for the whole world  - all administrative levels
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

from datetime import datetime
starttime=datetime.now()
print "PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Local Variables (TO BE EDITED BY THE USER)
SMOD_RAC_Mos = "F:\\JRC-FAO\\Data\\2_Outputs\\SMOD_RAC\\SMOD_RAC_mos_aggregated.tif"
admraster = "F:\\JRC-FAO\\Data\\1_Input\\AdminBoundaries\\g2015_2014_2\GAUL2015.gdb\\gaul_54009_500"
STATStable = "F:\\JRC-FAO\\Data\\2_Outputs\\CountryStats\\StatsGAUL_Level1.gdb\\TabAreas_SMOD_RAC_LVST_world"
gaul_L2 = "F:\\JRC-FAO\\Data\\2_Outputs\\CountryStats\\StatsGAUL_Level2.gdb"
gaul_L3 = "F:\\JRC-FAO\\Data\\2_Outputs\\CountryStats\\StatsGAUL_Level3.gdb"

# Tabulate Areas for the whole world - all administrative levels
TabulateArea(admraster,"Value",SMOD_RAC_Mos,"Value",STATStable,"500")
arcpy.TableToTable_conversion(STATStable, gaul_L2, "TabAreas_SMOD_RAC_LVST_world")
arcpy.TableToTable_conversion(STATStable, gaul_L3, "TabAreas_SMOD_RAC_LVST_world")
    
endtime=datetime.now()
totaltime= endtime-starttime
print ' '
print 'END OF PROCEDURE. Elapsed time: ', totaltime
print ' '



